name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Download latest Dalamud build
        run: |
          curl -O https://ottercorp.github.io/dalamud-distrib/latest.7z
          mkdir BlindBoxPlugin/Dalamud
          7z x latest.7z -oBlindBoxPlugin/Dalamud
      - name: Build
        run: dotnet build BlindBoxPlugin -c Release -o build
        env:
          DALAMUD_HOME: ${{ github.workspace }}/BlindBoxPlugin/Dalamud
      - name: Upload Files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build/BlindBoxPlugin/

  deploy:
    name: Deploy
    runs-on: windows-latest
    needs: build
    if: ${{ github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Get Tag Name
        shell: bash
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Upload Release Assets
        run: gh release upload --clobber ${{ env.TAG_NAME }} build/latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run generator
        run: .\.github\scripts\Make-Repo.ps1
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: Update repo"
          git push
