name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Download latest Dalamud build
        run: |
          curl -O https://goatcorp.github.io/dalamud-distrib/latest.zip
          mkdir BlindBoxPlugin/Dalamud
          unzip latest.zip -d ./BlindBoxPlugin/Dalamud
      - name: Build
        run: dotnet build BlindBoxPlugin -c Release -o build
        env:
          DalamudLibPath: ${{ github.workspace }}/Dalamud/
      - name: Upload Files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build/BlindBoxPlugin/

  deploy:
    name: Deploy
    runs-on: windows-latest
    needs: build
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Run generator
        run: .\.github\scripts\Make-Repo.ps1
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: Update repo"
          git push
      - name: Set Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Upload Release Assets
        run: gh release upload --clobber ${{ env.TAG_NAME }} build/latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
